components {
  id: "collisionhandler"
  component: "/scripts/veggiehandler.script"
}
components {
  id: "veggiePop"
  component: "/main/veggiePop.particlefx"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"Carrot\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/images.atlas\"\n"
  "}\n"
  ""
  scale {
    x: 7.860794
    y: 7.792706
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 8.0\n"
  "friction: 0.5\n"
  "restitution: 0.0\n"
  "group: \"carrot\"\n"
  "mask: \"floor\"\n"
  "mask: \"bag\"\n"
  "mask: \"carrot\"\n"
  "mask: \"greenPepper\"\n"
  "mask: \"onion\"\n"
  "mask: \"radish\"\n"
  "mask: \"garlic\"\n"
  "mask: \"broccoli\"\n"
  "mask: \"eggplant\"\n"
  "mask: \"cucumber\"\n"
  "mask: \"corn\"\n"
  "mask: \"pumpkin\"\n"
  "mask: \"potato\"\n"
  "mask: \"chilipepper\"\n"
  "mask: \"outofbounds\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      y: 273.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 1\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -7.0\n"
  "      y: -304.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 2\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -7.0\n"
  "      y: -538.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -8.0\n"
  "      y: -437.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 4\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -8.0\n"
  "      y: -437.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 5\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -1.0\n"
  "      y: -689.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -8.0\n"
  "      y: -777.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 7\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -7.0\n"
  "      y: -133.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 8\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -5.0\n"
  "      y: 92.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 9\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -4.0\n"
  "      y: -235.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 10\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -4.0\n"
  "      y: 323.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 11\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -8.0\n"
  "      y: -806.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 12\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -20.0\n"
  "      y: 672.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.11815094\n"
  "      w: 0.9929956\n"
  "    }\n"
  "    index: 13\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 45.0\n"
  "      y: 677.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.14860946\n"
  "      w: 0.9888959\n"
  "    }\n"
  "    index: 16\n"
  "    count: 3\n"
  "  }\n"
  "  data: 206.03053\n"
  "  data: 247.6803\n"
  "  data: 161.01366\n"
  "  data: 138.61269\n"
  "  data: 154.1218\n"
  "  data: 154.1218\n"
  "  data: 97.28053\n"
  "  data: 76.81316\n"
  "  data: 200.39694\n"
  "  data: 227.97539\n"
  "  data: 175.95703\n"
  "  data: 195.3789\n"
  "  data: 76.81316\n"
  "  data: 80.438225\n"
  "  data: 179.14613\n"
  "  data: 10.0\n"
  "  data: 80.438225\n"
  "  data: 179.14613\n"
  "  data: 10.0\n"
  "}\n"
  "bullet: true\n"
  ""
}
